all:
	g++ -std=c++98 -o cyoa-step1 -pedantic -Wall -Werror -ggdb3 -std=gnu++98 cyoa-step1.cpp Page.cpp Tool.cpp
	g++ -std=c++98 -o cyoa-step2 -pedantic -Wall -Werror -ggdb3 -std=gnu++98 cyoa-step2.cpp Page.cpp Tool.cpp Game.cpp
	g++ -std=c++98 -o cyoa-step3 -pedantic -Wall -Werror -ggdb3 -std=gnu++98 cyoa-step3.cpp Page.cpp Tool.cpp Game.cpp

clean:
	rm -f $(OBJS) $(OUT)

